// import { Toaster as Sonner } from "@/components/ui/sonner";
import AdminRedirectClient from '@/components/client/AdminRedirectClient';
import QueryProvider from '@/components/client/QueryProvider';
import TooltipWrapper from '@/components/client/TooltipWrapper';
import { Footer } from '@/components/layout/Footer';
import { Navbar } from '@/components/layout/Navbar';
// // import { Footer } from '@/components/layout/Footer';
// // import { Navbar } from '@/components/layout/Navbar';
// // import QueryProvider from '@/components/client/QueryProvider';
// // import TooltipWrapper from '@/components/client/TooltipWrapper';
// // import AdminRedirectClient from '@/components/client/AdminRedirectClient';

// export const metadata = {
//   title: "Your App Name",
//   description: "Your app description",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <QueryProvider>
//           <TooltipWrapper>
//             <AdminRedirectClient>
//               <div className="flex flex-col min-h-screen">
//                 <Navbar />
//                 <main className="flex-grow">{children}</main>
//                 <Footer />
//               </div>
//               <Sonner />
//             </AdminRedirectClient>
//           </TooltipWrapper>
//         </QueryProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'treehub-automation',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <TooltipWrapper>
            <AdminRedirectClient>
              <Navbar />
              {children}
              <Footer />
            </AdminRedirectClient>
          </TooltipWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
