// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swbdiwalryyejtupyptu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3YmRpd2Fscnl5ZWp0dXB5cHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MTI2NTUsImV4cCI6MjA1MDk4ODY1NX0.b2_n6hKV3ha3E9LLHKbJgIGR0KFLp2HDYU2qI1Jzx6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);